name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  id-token: write

jobs:
  detect:
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/detect-service.yaml@main
    with:
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}

  build:
    needs: detect
    if: ${{ needs.detect.outputs.services != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/build-service.yaml@main
    with:
      service: ${{ matrix.service }}
      image_tag: ${{ github.sha }}

  scan:
    needs: [detect, build]
    if: ${{ needs.detect.outputs.services != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/security-scan.yaml@main
    with:
      image: local/${{ matrix.service }}:${{ github.sha }}
      image_artifact: image-${{ matrix.service }}-${{ github.sha }}

  push_image:
    needs: [detect, scan]
    if: ${{ needs.detect.outputs.services != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/push-image.yaml@main
    with:
      service: ${{ matrix.service }}
      image_tag: ${{ github.sha }}
      image_artifact: image-${{ matrix.service }}-${{ github.sha }}
    secrets: inherit

  update_gitops:
    needs: [detect, push_image]
    if: ${{ needs.detect.outputs.services != '[]' }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/update-gitops.yaml@main
    with:
      services: ${{ needs.detect.outputs.services }}
      image_tag: ${{ github.sha }}
      pr_number: ${{ github.event.pull_request.number }}
      gitops_repo: Muhammad-Ibra3/platform-engineering-project
    secrets: inherit