name: CI

on:
  pull_request:
    types: 
      - opened

    

jobs:
  detect:
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/detect-service.yaml@main

  build:
    needs: detect
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/build-service.yaml@main
    with:
      service: ${{ matrix.service }}
      image_tag: ${{ github.sha }}

  scan:
    needs: [detect, build]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/security-scan.yaml@main
    with:
      image: local/${{ matrix.service }}:${{ github.sha }}
      image_artifact: image-${{ matrix.service }}-${{ github.sha }}

  sign:
    needs: [detect, scan]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/sign-image.yaml@main
    with:
      image_artifact: image-${{ matrix.service }}-${{ github.sha }}

  push_image:
    needs: [detect, scan, sign]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/push-image.yaml@main
    with:
      service: ${{ matrix.service }}
      image_tag: ${{ github.sha }}
      image_artifact: image-${{ matrix.service }}-${{ github.sha }}
    secrets: inherit

  update_gitops:
    needs: [detect, push_image]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/ci-tasks/update-gitops.yaml@main
    with:
      service: ${{ matrix.service }}
      image_tag: ${{ github.sha }}
      gitops_repo: Muhammad-Ibra3/platform-engineering-project
    secrets: inherit
