name: Destroy Preview

on:
  pull_request:
    types: [closed]

jobs:

  destroy:

    uses: Muhammad-Ibra3/platform-engineering-project/.github/workflows/preview-envs/preview-destroy.yaml@main

    with:
      pr_number: ${{ github.event.pull_request.number }}

    secrets: inherit